In [7]:
#import libraries
import os 
import pandas as pd # pacote para manipular os dados
import numpy as np # pacote para numeros 
import matplotlib.pyplot as plt # pacote para visualização dos dados
import seaborn as sns  # pacote para visualização dos dados

In [11]:
#importando a base 
df = pd.read_csv('../DATABASE/base_estudos.csv')

In [13]:
df.head()

,id_produto,id_contrato,id_cliente,data_entrada,valor_fin,qtde_prest,juros_efet,data_entrada.1,data_final,provisao,...,setor,situacao,rating_atual,linha_fin,tipo_a,tipo_b,tipo_c,tipo_d,garantia,valor_garantia
0,10707,30560012,212806,42349,151605.74,63.0,0.246781,42349,44607,0,...,SETOR PRIVADO,ADIMPLENTE,AA,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,245000.0
1,10707,30450012,212849,42367,133864.13,62.0,0.246802,42367,44607,0,...,SETOR PRIVADO,ADIMPLENTE,AA,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,219000.0
2,10707,31260012,212857,42349,156163.26,65.0,0.246774,42349,44669,45392,...,SETOR PRIVADO,ADIMPLENTE,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,245000.0
3,10707,31540015,212903,42349,132834.93,67.0,0.246793,42349,44727,397,...,SETOR PRIVADO,ADIMPLENTE,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,197000.0
4,10707,30570018,212911,42349,147130.53,63.0,0.246785,42349,44607,41467,...,SETOR PRIVADO,ADIMPLENTE,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,268000.0

In [14]:
#data info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2552 entries, 0 to 2551
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_produto       2552 non-null   int64
 1   id_contrato      2552 non-null   int64
 2   id_cliente       2552 non-null   int64
 3   data_entrada     2552 non-null   int64
 4   valor_fin        2552 non-null   float64
 5   qtde_prest       2551 non-null   float64
 6   juros_efet       2552 non-null   object
 7   data_entrada.1   2552 non-null   int64
 8   data_final       2552 non-null   int64
 9   provisao         2552 non-null   int64
 10  fat              2552 non-null   int64
 11  rating_operacao  2552 non-null   object
 12  rating_cliente   2552 non-null   object
 13  ra               2552 non-null   object
 14  porte            2552 non-null   object
 15  setor            2552 non-null   object
 16  situacao         2552 non-null   object
 17  rating_atual     2552 non-null   object
 18  linha_fin        2552 non-null   object
 19  tipo_a           2552 non-null   object
 20  tipo_b           2552 non-null   object
 21  tipo_c           2552 non-null   object
 22  tipo_d           2552 non-null   object
 23  garantia         2552 non-null   object
 24  valor_garantia   2537 non-null   float64
dtypes: float64(3), int64(8), object(14)
memory usage: 498.6+ KB

In [15]:
df.columns

Index(['id_produto', 'id_contrato', 'id_cliente', 'data_entrada', 'valor_fin',
       'qtde_prest', 'juros_efet', 'data_entrada.1', 'data_final', 'provisao',
       'fat', 'rating_operacao', 'rating_cliente', 'ra', 'porte', 'setor',
       'situacao', 'rating_atual', 'linha_fin', 'tipo_a', 'tipo_b', 'tipo_c',
       'tipo_d', 'garantia', 'valor_garantia'],
      dtype='object')

In [25]:
#drop uniportant variables 
drop_cols = ['id_produto', 'id_contrato', 'id_cliente', 'data_entrada','data_entrada.1', 'data_final'] 
df_clean = df.drop(drop_cols, axis=1)

#separando as variáveis por tipo (quantitativa e categórica)
---- quant_var = ['valor_fin','qtde_prest', 'juros_efet', 'provisao','fat', 'valor_garantia']
df_cat_var = df_clean.drop(quant_var, axis=1)

In [29]:
df_quant_var.head()

AttributeError: 'list' object has no attribute 'head'

In [28]:
df_cat_var.head()

,rating_operacao,rating_cliente,ra,porte,setor,situacao,rating_atual,linha_fin,tipo_a,tipo_b,tipo_c,tipo_d,garantia
0,AA,B,RA de Santos,PF,SETOR PRIVADO,ADIMPLENTE,AA,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos
1,AA,B,RA de Santos,PF,SETOR PRIVADO,ADIMPLENTE,AA,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos
2,A,B,RA de Santos,PF,SETOR PRIVADO,ADIMPLENTE,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos
3,A,A,RA de Santos,PF,SETOR PRIVADO,ADIMPLENTE,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos
4,A,A,RA de Santos,PF,SETOR PRIVADO,ADIMPLENTE,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos