In [1]:
#import libraries
import os 
import pandas as pd # pacote para manipular os dados
import numpy as np # pacote para numeros 
import matplotlib.pyplot as plt # pacote para visualização dos dados
import seaborn as sns  # pacote para visualização dos dados

In [43]:
#importando a base 
df = pd.read_csv('../DATABASE/base_estudos.csv')

In [68]:
df

,id_produto,id_contrato,id_cliente,data_entrada,valor_fin,qtde_prest,juros_efet,data_entrada.1,data_final,provisao,...,rating_atual,linha_fin,tipo_a,tipo_b,tipo_c,tipo_d,garantia,valor_garantia,fin_fat,fat_log
0,10707,30560012,212806,42349,151605.74,63.0,0.246781,42349,44607,0,...,AA,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,245000.00,20.265438,8.920122
1,10707,30450012,212849,42367,133864.13,62.0,0.246802,42367,44607,0,...,AA,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,219000.00,20.651671,8.776784
2,10707,31260012,212857,42349,156163.26,65.0,0.246774,42349,44669,45392,...,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,245000.00,0.162606,13.775082
3,10707,31540015,212903,42349,132834.93,67.0,0.246793,42349,44727,397,...,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,197000.00,0.132070,13.821289
4,10707,30570018,212911,42349,147130.53,63.0,0.246785,42349,44607,41467,...,A,PRO CAMINHONEIRO,ME,RT,PRIV,BNDES,Alienação Fiduciaria Veículos,268000.00,0.180865,13.609080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2547,61000,66300002,1433237,43658,560763.83,120.0,0.478414,43658,47304,565069,...,B,FUNGETUR,PI,RT,PRIV,FUNGETUR,Hipoteca 1º grau Imov Residencial,354000.00,560763.830000,0.000000
2548,61000,80050000,2487080,43854,53194.04,120.0,1.242.562,43854,47490,159906,...,C,FUNGETUR,PI,RT,PRIV,FUNGETUR,Alienação Fiduciaria Veículos,105292.20,53194.040000,0.000000
2549,61018,58320008,683159,43312,4793407.28,60.0,0.414216,43312,45145,0,...,AA,FUNGETUR,ME,RT,PRIV,FUNGETUR,Alienação Fiduciária Imóvel,37280000.00,0.005888,20.517598
2550,61018,58750002,727970,43515,182281.79,60.0,0.753472,43515,45327,550677,...,C,FUNGETUR,ME,RT,PRIV,FUNGETUR,FDA,191773.14,182281.790000,0.000000
2551,61018,76760006,2252112,43853,64000.00,60.0,0.585692,43853,45663,64141,...,B,FUNGETUR,ME,RT,PRIV,FUNGETUR,FGI - Crédito Livre,51200.00,0.000760,18.249312

In [44]:
#data info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2552 entries, 0 to 2551
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_produto       2552 non-null   int64
 1   id_contrato      2552 non-null   int64
 2   id_cliente       2552 non-null   int64
 3   data_entrada     2552 non-null   int64
 4   valor_fin        2552 non-null   float64
 5   qtde_prest       2551 non-null   float64
 6   juros_efet       2552 non-null   object
 7   data_entrada.1   2552 non-null   int64
 8   data_final       2552 non-null   int64
 9   provisao         2552 non-null   int64
 10  fat              2552 non-null   int64
 11  rating_operacao  2552 non-null   object
 12  rating_cliente   2552 non-null   object
 13  ra               2552 non-null   object
 14  porte            2552 non-null   object
 15  setor            2552 non-null   object
 16  situacao         2552 non-null   object
 17  rating_atual     2552 non-null   object
 18  linha_fin        2552 non-null   object
 19  tipo_a           2552 non-null   object
 20  tipo_b           2552 non-null   object
 21  tipo_c           2552 non-null   object
 22  tipo_d           2552 non-null   object
 23  garantia         2552 non-null   object
 24  valor_garantia   2537 non-null   float64
dtypes: float64(3), int64(8), object(14)
memory usage: 498.6+ KB

In [45]:
# mostra o nome de todas as colunas
df.columns

Index(['id_produto', 'id_contrato', 'id_cliente', 'data_entrada', 'valor_fin',
       'qtde_prest', 'juros_efet', 'data_entrada.1', 'data_final', 'provisao',
       'fat', 'rating_operacao', 'rating_cliente', 'ra', 'porte', 'setor',
       'situacao', 'rating_atual', 'linha_fin', 'tipo_a', 'tipo_b', 'tipo_c',
       'tipo_d', 'garantia', 'valor_garantia'],
      dtype='object')

In [46]:
#drop duplicate rows 
#df_ = df.drop_duplicates(keep='first')

In [47]:
#shape of the data
df.shape

(2552, 25)

In [51]:
#drop uniportant variables 
drop_cols = ['id_produto', 'id_contrato', 'id_cliente', 'data_entrada','data_entrada.1', 'data_final'] 
df_clean = df.drop(drop_cols, axis=1)

In [52]:
#criando variáveis quantitativas
# razão valor financiado/faturamento
df['fin_fat'] = df['valor_fin']/df['fat']

# log do faturamento
df['fat_log'] = np.log(df['fat'])

# prazo 
## df['prazo_dias'] = df['data_entrada'] - df['data_final']

In [58]:
#separando as variáveis por tipo (quantitativa e categórica)
#variáveis categóricas
quant_var = ['valor_fin','qtde_prest', 'juros_efet', 'provisao','fat', 'valor_garantia','fin_fat', 'fat_log']
df_cat_var = df_clean.drop(quant_var, axis=1)

In [59]:
# variáveis quantitativas
df_quant_var = df_clean.drop(df_cat_var, axis=1)

In [65]:
round(df_quant_var,2)

,valor_fin,qtde_prest,juros_efet,provisao,fat,valor_garantia,fin_fat,fat_log
0,151605.74,63.0,0.246781,0,7481,245000.00,20.27,8.92
1,133864.13,62.0,0.246802,0,6482,219000.00,20.65,8.78
2,156163.26,65.0,0.246774,45392,960378,245000.00,0.16,13.78
3,132834.93,67.0,0.246793,397,1005795,197000.00,0.13,13.82
4,147130.53,63.0,0.246785,41467,813483,268000.00,0.18,13.61
...,...,...,...,...,...,...,...,...
2547,560763.83,120.0,0.478414,565069,1,354000.00,560763.83,0.00
2548,53194.04,120.0,1.242.562,159906,1,105292.20,53194.04,0.00
2549,4793407.28,60.0,0.414216,0,814103582,37280000.00,0.01,20.52
2550,182281.79,60.0,0.753472,550677,1,191773.14,182281.79,0.00
2551,64000.00,60.0,0.585692,64141,84251117,51200.00,0.00,18.25

In [66]:
df_quant_var.head()

,valor_fin,qtde_prest,juros_efet,provisao,fat,valor_garantia,fin_fat,fat_log
0,151605.74,63.0,0.246781,0,7481,245000.0,20.265438,8.920122
1,133864.13,62.0,0.246802,0,6482,219000.0,20.651671,8.776784
2,156163.26,65.0,0.246774,45392,960378,245000.0,0.162606,13.775082
3,132834.93,67.0,0.246793,397,1005795,197000.0,0.132070,13.821289
4,147130.53,63.0,0.246785,41467,813483,268000.0,0.180865,13.609080

In [69]:
#Análise descritiva variáveis quantitativas (sumary)
df_quant_var.describe()

,valor_fin,qtde_prest,provisao,fat,valor_garantia,fin_fat,fat_log
count,2.552000e+03,2551.000000,2.552000e+03,2.552000e+03,2.537000e+03,2.552000e+03,2552.000000
mean,7.441381e+05,48.000000,2.877312e+06,4.746712e+08,9.501178e+05,6.550484e+04,16.797877
std,2.223146e+06,24.700528,5.131532e+07,1.247498e+09,4.019448e+06,9.254239e+05,4.003320
min,8.085800e+02,1.000000,0.000000e+00,1.000000e+00,0.000000e+00,9.376647e-06,0.000000
25%,5.461489e+04,34.000000,1.238425e+04,2.668803e+06,4.243968e+04,8.122299e-04,14.797140
50%,1.394400e+05,34.000000,5.444250e+04,4.176877e+07,1.157296e+05,3.342867e-03,17.547654
75%,3.215124e+05,60.000000,1.976340e+05,2.230333e+08,2.800000e+05,5.285864e-02,19.222831
max,3.368884e+07,238.000000,2.304914e+09,9.987347e+09,8.917560e+07,3.219690e+07,23.024585

In [ ]:
## Selecionar somente dados tipo.a = PI